config/routes.rb
Rails.application.routes.draw do

  mount Spree::Core::Engine, at: '/store'
          mount RailsAdmin::Engine => 'store/admin', as: 'rails_admin'
  get 'home/index'

    root 'home#index'

resources :orders
namespace :admin do
  resources :orders
end
  

end

app/models/order.rb
class Order < ActiveRecord::Base
  include MailForm::Delivery

	attributes :name, :validate => true
	attributes :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
	attributes :description, :validate => true

	 #validates :name, presence: true
	 #validates :email, presence: true
	 #validates :description, presence: true, length: { minimum: 20 }

	

	 def headers
    {
      :subject => "New Custom Order Request",
      :to => "emma.s.ife@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
                    
end

app/controllers/admin/orders_controller.rb
class OrdersController < ApplicationController

	 def index
    	@orders = Order.all
  	end
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	 def index
    	@orders = Order.all
  	end
	def new
		@order = Order.new
	end

	def edit
  		@order = Order.find(params[:id])
	end

	def create
		@order = Order.new(order_params)
	    @order.request = request
	    if @order.deliver
	      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
	      redirect_to @order

	    else
	      flash.now[:error] = 'Cannot send message.'
	      render :new
	    end
		#@order = Order.new(order_params)

		#if @order.save
		#	redirect_to @order
		#else
		#	render 'new'
		#end
	end


	def update

		@order = Order.find(params[:id])
		
		if @order.update(order_params)
			@newCustomOrder = Spree::Product.new(name: @order.name, price: @order.price, description: @order. description, available_on: Time.now)
			@newCustomOrder.save(validate: false) 
		  #render '/spree/admin/products/new'
		 #redirect_to  new_admin_product_path 
		  redirect_to '/store/admin/products'

		else
		  render 'edit'
		end
	end

	def show
    	@order = Order.find(params[:id])
  	end



	private
		def order_params
			params.require(:order).permit(:name, :email, :description, :price)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CustomOrder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/mail_form/contact.erb
<h4 style="text-decoration:underline"><%= message.subject %></h4>

<% @resource.mail_form_attributes.each do |attribute, value|
  next if value.blank? %>

  <p><b><%= @resource.class.human_attribute_name(attribute) %>:</b>
  <%= case value
    when /\n/
      raw(simple_format(h(value)))
    when Time, DateTime, Date
      I18n.l(value)
    else
      value
    end
  %></p>
<% end %>

Click here to create order

app/views/orders/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/orders/edit.html.erb
<h1>Update Order With Price</h1>
 
<%= form_for :order, url: order_path(@order), method: :patch do |f| %>
 
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@order.errors.count, "error") %> prohibited
        this order from being saved:
      </h2>
      <ul>
        <% @order.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 <p><b>Name:</b><%= @order.name %></p>
 <p><b>Email</b> <%= @order.email%></p>
 <p><b>Description:</b> <%=@order.description%></p>
  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>
 
 

  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Custom Order Requests</h1>
 
<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Description</th>
  </tr>
 
  <% @orders.each do |order| %>
    <tr>
      <td><%= order.name %></td>
      <td><%= order.email %></td>
      <td><%= order.description %></td>
    </tr>
  <% end %>
</table>

app/views/orders/new.html.erb
<h1>Custom Order Form</h1>




<%= form_for :order, url: orders_path do |f| %>
  <% if @order.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@order.errors.count, "error") %> prohibited
          this order from being saved:
        </h2>
        <ul>
          <% @order.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/orders/order_email.html.erb
From: <%= @order.name %>

Email: <%= @order.email %>

Request: <%= @order.description %>

Click Here To Create Custom Order

app/views/orders/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>
 
<p>
  <strong>Email:</strong>
  <%= @order.email %>
</p>

<p>
  <strong>Description:</strong>
  <%= @order.description %>
</p>